language: node_js
node_js:
  - "4.1"
  - "4.0"
#before_install:
#  - npm install -g grunt-cli
install:
  - npm install
  - webdriver-manager update --standalone --chrome --firefox
  - npm run init
#before_script:
#  - "export DISPLAY=:99.0"
#  - sh -e /etc/init.d/xvfb start - nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &" - sleep 5
before_script:
  - npm install -g grunt-cli
before_install:
  - "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -"
  - "sudo sh -c 'echo \"deb http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google.list'"
  - "sudo apt-get update"
  - "sudo apt-get install google-chrome-stable"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
#script:
#  - grunt travis-protractor
#after_success: 'npm run coveralls'
